### ISSUE TITLE
Overhaul Results Render

### ISSUE THREAD

**Issue by marcaaron** [marcaaron/ww-calc-2.0#26]
Just going to drop these here via Jen since whoever handles this will probably want to tackle all of this stuff at once.

- [x] Remove Calculator Results.

- [x] Don’t show your current monthly costs at all. Remove.
- [x] Replace with ‘Your New Projected Cost Per Household’. (The last thing they entered was their
current, so the first thing we want to show is the new)
- [x] Under Cost Breakdown, where we’re showing our work, remove the spaces in between. People
won’t care about this as much and it takes up a lot of room and forces more scrolling.
- [x] If there is a savings, show both xx/mo and xx/yr. Then show a Donate Button with text. See
[Savings Result PDF](https://github.com/marcaaron/ww-calc-2.0/blob/master/notes/Savings%20result.pdf)
- [x] If there’s not a savings, show a text box –we’ll need to tweak this a bit. Then show a Donate
Button with text. See No Savings Result PDF

_Last section will be called Your Benefit (whether it’s a savings or not)_

proposing we maybe only make this read YOUR BENEFIT in the case of non-savings...

**Comment by dentemple** [comment]
I'll tackle this one.

**Comment by marcaaron** [comment]
Nice work!!!

Just noticed one inconsistency... For an individual we're seeing 'TOTAL SAVINGS' and for a household we're getting 'Your Benefit'. I'll have to get confirmation from Jen, but I'm assuming the idea was to have the last section be labeled 'YOUR BENEFIT' in all cases and in the case of money saved people would see their savings and in the case of no savings people would see some sort of message.

I personally think it should still show TOTAL SAVINGS or YOUR SAVINGS in the case of money saved... since 'benefit' doesn't really have the same kick as 'savings' to someone who is trying to save money, but works better to frame the situation for someone who won't be saving.
