### ISSUE TITLE
Formatting: AGI Question

### ISSUE THREAD

**Issue by marcaaron** [marcaaron/ww-calc-2.0#33]
_If possible, reduce the text of the Form/Lines so that user doesn't have to scroll to get to Next._  

_Or widen text box?_

Widening the tip text box will effect every question since they are share a common css class. They also adjust responsively. Keep in mind the changes taking place at all screen resolutions if this seems like a better solution than reducing font text. A combination of the two strategies might be best.

**Comment by couchpilotnye** [comment]
This looks great. Done.
