### ISSUE TITLE
Bug: Business Results Color Bars Not Rendering Consistently Across Browsers

### ISSUE THREAD

**Issue by marcaaron** [marcaaron/ww-calc-2.0#41]
For Current Healthcare Costs and Projected Healthcare Costs in the Business Results render page we have reports that the colored bars indicating annual healthcare costs appear to be centered vs. left-aligned. I have not been able to replicate this. Maybe someone can investigate?

**Comment by HarryAKA** [comment]
Also wasn't able to reproduce in Chrome, Safari, or Firefox. Any additional details on this?

**Comment by marcaaron** [comment]
Not yet, asked for pics, but never received.

**Comment by couchpilotnye** [comment]
![image](https://user-images.githubusercontent.com/37560660/38594132-ca3306d6-3cf9-11e8-87da-ab4044105f41.png)

**Comment by couchpilotnye** [comment]
I misinterpreted this. We can close.
