### ISSUE TITLE
Individual - NEW STEP - 

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#55]
Add new step. Content:

Include costs incurred over the course of the year for every member of your Household, such as:     
• Co-Pays     
• Prescriptions*     
• Medical Bills not covered/denied by Insurance     
• Emergency Room or Clinic Visits     
• Deductibles     

*Note: the most you’ll pay for prescriptions with I-1600 Universal Healthcare is $250 per adult per year

****************************
Calculation: take the amount entered, divide by 12 and add to previous monthly costs step.

**Comment by marcaaron** [comment]
Do we have a preferred suggested title/question to accompany this step? 
I'm going to temporarily put 'Your Current Yearly Additional Medical Costs'.

**Comment by couchpilotnye** [comment]
I’m sorry, Marc! 

 

I never transferred the title over from my spreadsheet. It’s: Your Current Out-of-Pocket Costs

 

While you’re in this step can you please delete what looks like an extra space between Deductibles and the Note?

**Comment by marcaaron** [comment]
Maybe we should be a bit more explicit about what we're asking here? The question before this one asks about 'monthly' premiums and then switches to 'yearly' I'm thinking people might get confused by 'Your Current Out-of-Pocket Costs' and assume we're asking for that figure per month if they don't read the tip text carefully.

**Comment by marcaaron** [comment]
How do you feel about 'Your Current Yearly Out-of-Pocket Costs' ?

**Comment by couchpilotnye** [comment]
Good with that. Thanks
