### ISSUE TITLE
Individual - Results/Content

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#56]
Now that we're adding a new step that requires adding them for a total, we should display it. 

Your Current Cost Per Household
$x/mo
($x/yr)
Your New Projected Cost Per Household 
$x/mo
($x/yr)

PROJECTED CONTRIBUTIONS
Income Contribution
$0/mo
Investment Profit Contribution
$0/mo
Per Child Premium
FREE x 1
Per Adult Premium *
$0/mo x 3

* See [Monthly Premium](https://i1600-wholewashington.nationbuilder.com/monthly_premium) for more info. Employers may choose to pay the Premium as part of their benefits.

**Comment by couchpilotnye** [comment]
Hi Marc, I wasn't clear on this one. What we need to add is this:
Your Current Cost Per Household
$x/mo
($x/yr)

We now have two steps that determine this amount so we need to show the total. (Previously, we took it out because it was the last thing the user entered just before results, so it was a repeat and not needed.)
Hope I'm making sense!

**Comment by couchpilotnye** [comment]
Can we re-open this one, please?

**Comment by marcaaron** [comment]
Sorry, I'm not sure what you're asking? The total we're displaying under "Your Current Cost Per Household" is the sum of monthly premiums and yearly medical expenses. Was there something else?

**Comment by couchpilotnye** [comment]
Where are we showing the Current Cost Per Household? You're saying that's currently on the Results screen? 

I'm not seeing that: 
![image](https://user-images.githubusercontent.com/37560660/38596429-465df2b4-3d06-11e8-93eb-a4bbe2f16e74.png)

**Comment by couchpilotnye** [comment]
All I see is New Projected.

**Comment by marcaaron** [comment]
My mistake, seems like I only edited the results for a single individual and not households with more than 1 person. Good catch. 👍

**Comment by marcaaron** [comment]
Should be fixed now.
