### ISSUE TITLE
Remove the information 'i' icon from Number of Adults step

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#61]
Remove the information 'i' icon from Number of Adults step

In all other cases, the i is used to give details on what's being entered. For this step, no help is needed and we're just setting the user up for the next step.

**Comment by marcaaron** [comment]
The icon is going to render for every question that has a tip. This will require some conditional rendering logic for the icon and probably a modification of the `questions.js` file to add a property to either every question with tip text or just the one question we're trying to modify.

We could add a `showIcon: false` flag to the Number of Adults question then in the `Question.js` component we'd want to render the icon if there is no such flag. Open to other suggestions.
