### ISSUE TITLE
Add Disclaimer to Front Page 

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/ww-calc-2.0#62]
Please add the following disclaimer to the bottom of the landing page:

This calculator provides an **_estimate_** of how I-1600 would impact your bottom line. If you have  significant partnership or capital income (e.g. more than $15,000 a year), you may want to consult a tax professional for a more complete assessment.

**Comment by marcaaron** [comment]
Are you wanting this to have the word "Disclaimer" appended to it ? Or just feature the text as written?

**Comment by couchpilotnye** [comment]
No need for the word Disclaimer. Looks good.
